create DATABASE ProteinDB;
GO



USE ProteinDB;

CREATE TABLE SPECIES(
	TaxID			INT			PRIMARY KEY,
	ScientificName	VARCHAR(50)	UNIQUE NOT NULL,
	Domain			VARCHAR(50),	
	Kingdom			VARCHAR(50),
	Phylum			VARCHAR(50),		
	Class			VARCHAR(50),
	Ordr			VARCHAR(50),
	Family			VARCHAR(50),
	Genre			VARCHAR(50)
);

CREATE TABLE PFUNCTION(
	ID	INT	PRIMARY KEY,
	Description	TEXT	
);

CREATE TABLE PUSER(
	ID				INT 			PRIMARY KEY,
	Name			VARCHAR(30)	NOT NULL,
	DateBirth		DATE,
	ProfilePicture	VARCHAR(30),
	University		VARCHAR(30),
	Profession		VARCHAR(30)	
);

CREATE TABLE CURATOR(
	User_ID			INT 		NOT NULL,
	DateOfContract	DATE		NOT NULL,
	PRIMARY KEY (User_ID),
	FOREIGN KEY (User_ID) REFERENCES PUSER(ID)		
);

CREATE TABLE GENE(
	Code			VARCHAR(20) PRIMARY KEY ,
	Name			VARCHAR(20)	,
	Size			INT,
	Sequence		TEXT	NOT NULL,
	GC_Content		INT,
	AT_Content		INT
);

CREATE TABLE PROTEIN_ENTRY(
	AccessionID		VARCHAR(20) PRIMARY KEY,
	Sequence		TEXT,
	ProteinType		VARCHAR(40),
	Gene_Code		VARCHAR(20),
	S_TaxID			INT,
	FOREIGN KEY (Gene_Code) REFERENCES GENE(Code),
	FOREIGN KEY (S_TaxID) REFERENCES SPECIES(TaxID)
);

CREATE TABLE DISEASE(
	ICD10Code		VARCHAR(20)	PRIMARY KEY,
	Name			VARCHAR(60)	NOT NULL,
);

CREATE TABLE PUBLICATION(
	ID				INT	PRIMARY KEY,
	Link			VARCHAR (50),
	Title			VARCHAR(300),	
	User_ID			INT	REFERENCES PUSER(ID),
	SubmitionDate	DATE  NOT NULL
);

CREATE TABLE PUB_AUTHOR(
	Publication_ID	INT NOT NULL,
	AuthorName		VARCHAR(50) NOT NULL,
	PRIMARY KEY (Publication_ID, AuthorName),
	FOREIGN KEY (Publication_ID) REFERENCES PUBLICATION(ID)
);

CREATE TABLE PROJECT(
	ID	INT	PRIMARY KEY,
	Description	TEXT
);


CREATE TABLE PARTICIPATES(
	User_ID	INT NOT NULL,
	Project_ID	INT NOT NULL,
	PRIMARY KEY (User_ID, Project_ID),
	FOREIGN KEY (User_ID) REFERENCES PUSER(ID),
	FOREIGN KEY (Project_ID) REFERENCES PROJECT(ID)
);

CREATE TABLE CAUSES(
	P_AccessionID		VARCHAR(20) 	NOT NULL,
	Disease_ICD10Code	VARCHAR(20)	NOT NULL,
	PRIMARY KEY(P_AccessionID, Disease_ICD10Code),
	FOREIGN KEY(P_AccessionID) REFERENCES PROTEIN_ENTRY(AccessionID),
	FOREIGN KEY(Disease_ICD10Code) REFERENCES DISEASE(ICD10Code)
);

CREATE TABLE INTERACTION(
	P_AccessionID	VARCHAR(20)	NOT NULL,
	P2_AccessionID	VARCHAR(20)	NOT NULL,
	PRIMARY KEY (P_AccessionID,P2_AccessionID),
	FOREIGN KEY (P_AccessionID) REFERENCES PROTEIN_ENTRY(AccessionID),
	FOREIGN KEY (P2_AccessionID) REFERENCES PROTEIN_ENTRY(AccessionID)
);

CREATE TABLE MENTION_PROTEIN(
	I_P_AccessionID		VARCHAR(20)	NOT NULL,
	Publication_ID		INT	NOT NULL,
	PRIMARY KEY (I_P_AccessionID, Publication_ID),
	FOREIGN KEY (I_P_AccessionID) REFERENCES PROTEIN_ENTRY (AccessionID),
	FOREIGN KEY(Publication_ID) REFERENCES PUBLICATION(ID)
);

CREATE TABLE APROVAL_MENTION_PROTEIN(
	Curator_ID 			INT NOT NULL,
	M_I_P_AccessionID 	VARCHAR(20)NOT NULL,
	M_Publication_ID	INT NOT NULL,
	DateOfApproval		DATE,
	PRIMARY KEY(Curator_ID, M_I_P_AccessionID, M_Publication_ID),
	FOREIGN KEY (Curator_ID) REFERENCES CURATOR (User_ID),
	FOREIGN KEY (M_I_P_AccessionID,M_Publication_ID ) REFERENCES MENTION_PROTEIN (I_P_AccessionID,Publication_ID )
	);


CREATE TABLE MENTION_FUNCTION
(	P_AccessionID 	VARCHAR(20)	NOT NULL,
	F_ID			INT	NOT NULL,
	Publication_ID	INT NOT NULL,
	PRIMARY KEY(P_AccessionID, F_ID, Publication_ID),
	FOREIGN KEY(P_AccessionID) REFERENCES PROTEIN_ENTRY(AccessionID),
	FOREIGN KEY(F_ID) REFERENCES PFUNCTION(ID),
	FOREIGN KEY(Publication_ID) REFERENCES PUBLICATION(ID)
);

CREATE TABLE APROVAL_MENTION_FUNCTION
(	Curator_ID			INT NOT NULL,
	M_F_P_AccessionID 	VARCHAR(20) NOT NULL,
	M_I_F_ID			INT NOT NULL,
	M_Publication_ID	INT NOT NULL,
	DateOfApproval		DATE,
	PRIMARY KEY(Curator_ID, M_F_P_AccessionID, M_I_F_ID,  M_Publication_ID, DateOfApproval),
	FOREIGN KEY (Curator_ID) REFERENCES CURATOR(User_ID),
	FOREIGN KEY (M_F_P_AccessionID, M_I_F_ID,M_Publication_ID) REFERENCES MENTION_FUNCTION(P_AccessionID, F_ID, Publication_ID)
);
