USE ProteinDB;

SELECT 'DEBUG';

CREATE TABLE SPECIES(
	TaxID			INT			PRIMARY KEY,
	ScientificName	VARCHAR(20)	UNIQUE NOT NULL,
	Life			VARCHAR(20),
	Domain			VARCHAR(20),	
	Kingdom			VARCHAR(20),
	Phylum			VARCHAR(20),		
	Class			VARCHAR(20),
	Ordr			VARCHAR(20),
	Family			VARCHAR(20),
	Genre			VARCHAR(20),
	Specie			VARCHAR(20)
);

SELECT 'DEBUG1';
CREATE TABLE PFUNCTION(
	ID	INT	PRIMARY KEY,
	Description	TEXT	
);

SELECT 'DEBUG2';
CREATE TABLE PUSER(
	ID				INT 			PRIMARY KEY,
	Name			VARCHAR(30)	NOT NULL,
	DateBirth		DATE,
	ProfilePicture	VARCHAR(30),
University		VARCHAR(30),
Profession		VARCHAR(30)	
);

SELECT 'DEBUG3';
CREATE TABLE CURATOR(
	User_ID			INT 		NOT NULL,
	DateOfContract	DATE		NOT NULL,
	PRIMARY KEY (User_ID),
	FOREIGN KEY (User_ID) REFERENCES PUSER(ID)		
);

SELECT 'DEBUG4';
CREATE TABLE GENE(
	Name			VARCHAR(20)	PRIMARY KEY,
	Size			INT,
	Sequence		VARCHAR(20)	NOT NULL,
	GC_Content		INT,
	AT_Content		INT
);

SELECT 'DEBUG5';
CREATE TABLE PROTEIN_ENTRY(
	AccessionID		VARCHAR(20) PRIMARY KEY,
	FullName		VARCHAR(100) UNIQUE NOT NULL,
	Sequence		VARCHAR(20),
	ProteinType		VARCHAR(20),
	Gene_Name		VARCHAR(20),
	S_TaxID			INT,
	FOREIGN KEY (Gene_Name) REFERENCES GENE(Name),
	FOREIGN KEY (S_TaxID) REFERENCES SPECIES(TaxID)
);

SELECT 'DEBUG6';
CREATE TABLE DISEASE(
	ICD10Code		VARCHAR(20)	PRIMARY KEY,
	Name			VARCHAR(20)	NOT NULL,
	Description		TEXT
);

SELECT 'DEBUG7';
CREATE TABLE PUBLICATION(
	ID				INT	PRIMARY KEY,
	Link			VARCHAR (50)	UNIQUE NOT NULL,
	User_ID			INT	REFERENCES PUSER(ID),
	SubmitionDate	DATE  NOT NULL
);

SELECT 'DEBUG8';
CREATE TABLE PUB_AUTHOR(
	Publication_ID	INT NOT NULL,
	AuthorName		VARCHAR(20) NOT NULL,
	PRIMARY KEY (Publication_ID, AuthorName),
	FOREIGN KEY (Publication_ID) REFERENCES PUBLICATION(ID)
);

SELECT 'DEBUG9';
CREATE TABLE PROJECT(
	ID	INT	PRIMARY KEY,
	Description	TEXT
);


SELECT 'DEBUG10';
CREATE TABLE PARTICIPATES(
	User_ID	INT NOT NULL,
	Project_ID	INT NOT NULL,
	PRIMARY KEY (User_ID, Project_ID),
	FOREIGN KEY (User_ID) REFERENCES PUSER(ID),
	FOREIGN KEY (Project_ID) REFERENCES PROJECT(ID)
);

SELECT 'DEBUG11';
CREATE TABLE CAUSES(
	P_AccessionID		VARCHAR(20) 	NOT NULL,
	Disease_ICD10Code	VARCHAR(20)	NOT NULL,
	PRIMARY KEY(P_AccessionID, Disease_ICD10Code),
	FOREIGN KEY(P_AccessionID) REFERENCES PROTEIN_ENTRY(AccessionID),
	FOREIGN KEY(Disease_ICD10Code) REFERENCES DISEASE(ICD10Code)
);

SELECT 'DEBUG12';
CREATE TABLE HAS_FUNCTION(
	P_AccessionID	VARCHAR(20)	NOT NULL,
	Function_ID	INT	NOT NULL,
	PRIMARY KEY (P_AccessionID, Function_ID),
	FOREIGN KEY (P_AccessionID) REFERENCES PROTEIN_ENTRY(AccessionID),
	FOREIGN KEY (Function_ID) REFERENCES PFUNCTION(ID)
);

SELECT 'DEBUG13';
CREATE TABLE INTERACTION(
	P_AccessionID	VARCHAR(20)	NOT NULL,
	P2_AccessionID	VARCHAR(20)	NOT NULL,
	PRIMARY KEY (P_AccessionID,P2_AccessionID),
	FOREIGN KEY (P_AccessionID) REFERENCES PROTEIN_ENTRY(AccessionID),
	FOREIGN KEY (P2_AccessionID) REFERENCES PROTEIN_ENTRY(AccessionID)
);

SELECT 'DEBUG14';
CREATE TABLE MENTION_INTERACTION(
	I_P_AccessionID		VARCHAR(20)	NOT NULL,
	I_P2_AccessionID	VARCHAR(20)	NOT NULL,
	Publication_ID		INT	NOT NULL,
	PRIMARY KEY (I_P_AccessionID, I_P2_AccessionID, Publication_ID),
	FOREIGN KEY (I_P_AccessionID, I_P2_AccessionID) REFERENCES INTERACTION (P_AccessionID, P2_AccessionID),
	FOREIGN KEY(Publication_ID) REFERENCES PUBLICATION(ID)
);

SELECT 'DEBUG15';
CREATE TABLE APROVAL_MENTION_INTERACTION(
	Curator_ID 			INT NOT NULL,
	M_I_P_AccessionID 	VARCHAR(20)NOT NULL,
	M_I_P2_AccessionID 	VARCHAR(20) NOT NULL,
	M_Publication_ID	INT NOT NULL,
	DateOfApproval		DATE,
	PRIMARY KEY(Curator_ID, M_I_P_AccessionID,M_I_P2_AccessionID, M_Publication_ID),
	FOREIGN KEY (Curator_ID) REFERENCES CURATOR (User_ID),
	FOREIGN KEY (M_I_P_AccessionID, M_I_P2_AccessionID,M_Publication_ID ) REFERENCES MENTION_INTERACTION (I_P_AccessionID,I_P2_AccessionID,Publication_ID ));


SELECT 'DEBUG16';
CREATE TABLE MENTION_FUNCTION
(	P_AccessionID 	VARCHAR(20)	NOT NULL,
	F_ID			INT	NOT NULL,
	Publication_ID	INT NOT NULL,
	PRIMARY KEY(P_AccessionID, F_ID, Publication_ID),
	FOREIGN KEY(P_AccessionID) REFERENCES PROTEIN_ENTRY(AccessionID),
	FOREIGN KEY(F_ID) REFERENCES PFUNCTION(ID),
	FOREIGN KEY(Publication_ID) REFERENCES PUBLICATION(ID)
);



SELECT 'DEBUG17';
CREATE TABLE APROVAL_MENTION_FUNCTION
(	Curator_ID			INT NOT NULL,
	M_F_P_AccessionID 	VARCHAR(20) NOT NULL,
	M_I_F_ID			INT NOT NULL,
	M_Publication_ID	INT NOT NULL,
	DateOfApproval		DATE,
	PRIMARY KEY(Curator_ID, M_F_P_AccessionID, M_I_F_ID,  M_Publication_ID, DateOfApproval),
	FOREIGN KEY (Curator_ID) REFERENCES CURATOR(User_ID),
	FOREIGN KEY (M_F_P_AccessionID, M_I_F_ID,M_Publication_ID) REFERENCES MENTION_FUNCTION(P_AccessionID, F_ID, Publication_ID)
);
